services:
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=postgresDB'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    ports:
      - '5432'

  spring-boot-url-shortener:
    image: kunalkrishna/spring-boot-url-shortener
    container_name: spring-boot-url-shortener
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgresDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - postgres